name: "PR"

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  lint-go:
    name: Run Go Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.26'
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: src/server/

  test-go:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.26'
      - uses: actions/checkout@v3
      - name: go build
        working-directory: src/server/
        run: go build ./...
      - name: go test
        working-directory: src/server/
        run: go test -race ./...
